#!/bin/bash
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

clear
echo -e "${BLUE}╔════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   D&D Play-by-Post Setup Wizard       ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════╝${NC}"
echo ""

# Check if .env already exists
if [ -f .env ]; then
    echo -e "${YELLOW}⚠ Warning: .env file already exists!${NC}"
    echo ""
    read -p "Do you want to overwrite it? (y/N): " overwrite
    if [[ ! $overwrite =~ ^[Yy]$ ]]; then
        echo -e "${RED}Setup cancelled.${NC}"
        exit 1
    fi
    echo ""
    echo "Creating backup: .env.backup.$(date +%Y%m%d_%H%M%S)"
    cp .env .env.backup.$(date +%Y%m%d_%H%M%S)
    echo ""
fi

echo -e "${CYAN}This wizard will configure your D&D Play-by-Post instance.${NC}"
echo -e "${CYAN}You only need to answer 2 questions - everything else is automatic!${NC}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Question 1: Domain
echo -e "${GREEN}Question 1 of 2: Domain Configuration${NC}"
echo ""
echo "Enter your domain name (e.g., dnd.example.com)"
echo -e "${YELLOW}Or enter 'localhost' for local development${NC}"
echo ""
read -p "Domain: " DOMAIN

# Validate domain
if [ -z "$DOMAIN" ]; then
    echo -e "${RED}Error: Domain cannot be empty${NC}"
    exit 1
fi

echo ""

# Question 2: Email (only if not localhost)
if [ "$DOMAIN" != "localhost" ]; then
    echo -e "${GREEN}Question 2 of 2: SSL Certificate Email${NC}"
    echo ""
    echo "Enter your email address for SSL certificate notifications"
    echo -e "${YELLOW}(Required by Let's Encrypt for certificate renewal alerts)${NC}"
    echo ""
    read -p "Email: " SSL_EMAIL
    
    if [ -z "$SSL_EMAIL" ]; then
        echo -e "${RED}Error: Email cannot be empty for production setup${NC}"
        exit 1
    fi
    
    ENABLE_SSL="true"
    echo ""
else
    ENABLE_SSL="false"
    echo -e "${YELLOW}Development mode selected - SSL disabled${NC}"
    echo ""
fi

# Advanced options (optional)
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
read -p "Configure advanced settings? (y/N): " advanced
echo ""

if [[ $advanced =~ ^[Yy]$ ]]; then
    echo -e "${GREEN}Advanced Configuration${NC}"
    echo ""
    
    read -p "JWT token expiration (minutes) [30]: " token_expire
    ACCESS_TOKEN_EXPIRE_MINUTES=${token_expire:-30}
    
    read -p "Enable debug mode? (y/N): " debug_mode
    if [[ $debug_mode =~ ^[Yy]$ ]]; then
        DEBUG="true"
        NODE_ENV="development"
    else
        DEBUG="false"
        NODE_ENV="production"
    fi
    echo ""
else
    # Smart defaults
    ACCESS_TOKEN_EXPIRE_MINUTES=30
    DEBUG="false"
    NODE_ENV="production"
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${GREEN}⚙ Generating Configuration...${NC}"
echo ""

# Generate secure secrets
echo -n "  Generating SECRET_KEY... "
SECRET_KEY=$(openssl rand -hex 32)
echo -e "${GREEN}✓${NC}"

echo -n "  Generating POSTGRES_PASSWORD... "
POSTGRES_PASSWORD=$(openssl rand -hex 16)
echo -e "${GREEN}✓${NC}"

echo -n "  Generating REDIS_PASSWORD... "
REDIS_PASSWORD=$(openssl rand -hex 16)
echo -e "${GREEN}✓${NC}"

# Smart URL configuration
if [ "$ENABLE_SSL" = "true" ]; then
    CORS_ORIGINS="https://$DOMAIN,https://www.$DOMAIN"
    API_URL="https://$DOMAIN"
    FRONTEND_URL="https://$DOMAIN"
    PUBLIC_API_URL="https://$DOMAIN"
    ORIGIN="https://$DOMAIN"
    echo -n "  Configuring HTTPS URLs... "
else
    CORS_ORIGINS="http://localhost,http://localhost:3000,http://localhost:5173"
    API_URL="http://localhost:8000"
    FRONTEND_URL="http://localhost:3000"
    PUBLIC_API_URL="http://localhost:8000"
    ORIGIN="http://localhost:3000"
    echo -n "  Configuring HTTP URLs... "
fi
echo -e "${GREEN}✓${NC}"

echo ""
echo -e "${GREEN}📝 Creating Configuration Files...${NC}"
echo ""

# Create .env file
cat > .env << EOF
# D&D Play-by-Post Configuration
# Auto-generated by setup.sh on $(date)
# DO NOT commit this file to version control!

# =============================================================================
# DOMAIN CONFIGURATION
# =============================================================================
DOMAIN=$DOMAIN
ENABLE_SSL=$ENABLE_SSL
${SSL_EMAIL:+SSL_EMAIL=$SSL_EMAIL}

# =============================================================================
# CORS CONFIGURATION
# =============================================================================
CORS_ORIGINS=$CORS_ORIGINS

# =============================================================================
# API & FRONTEND URLs
# =============================================================================
API_URL=$API_URL
FRONTEND_URL=$FRONTEND_URL
PUBLIC_API_URL=$PUBLIC_API_URL
ORIGIN=$ORIGIN

# =============================================================================
# APPLICATION SECURITY
# =============================================================================
SECRET_KEY=$SECRET_KEY
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=$ACCESS_TOKEN_EXPIRE_MINUTES

# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=dnd_pbp
POSTGRES_USER=dnd
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# =============================================================================
# REDIS CONFIGURATION
# =============================================================================
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=$REDIS_PASSWORD

# =============================================================================
# PORT CONFIGURATION
# =============================================================================
BACKEND_PORT=8000
FRONTEND_PORT=3000
HTTP_PORT=80
HTTPS_PORT=443
ADMINER_PORT=8080

# =============================================================================
# APPLICATION SETTINGS
# =============================================================================
DEBUG=$DEBUG
NODE_ENV=$NODE_ENV
EOF

echo -n "  Created .env... "
echo -e "${GREEN}✓${NC}"

# Create secrets backup file
cat > .env.secrets << EOF
# D&D Play-by-Post Secrets Backup
# Created: $(date)
# 
# ⚠️  IMPORTANT: Keep this file safe and secure!
# These secrets are required to access your database and decrypt user sessions.
# If you lose these, you will lose access to your data.
#
# Store this file in a secure location (encrypted backup, password manager, etc.)

SECRET_KEY=$SECRET_KEY
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
REDIS_PASSWORD=$REDIS_PASSWORD
EOF

chmod 600 .env.secrets
echo -n "  Created .env.secrets (backup)... "
echo -e "${GREEN}✓${NC}"

echo ""

# SSL Setup
if [ "$ENABLE_SSL" = "true" ]; then
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo -e "${GREEN}🔒 SSL Certificate Setup${NC}"
    echo ""
    echo -e "${YELLOW}Before obtaining SSL certificates, please ensure:${NC}"
    echo "  1. Your domain ($DOMAIN) points to this server's IP"
    echo "  2. Ports 80 and 443 are open in your firewall"
    echo "  3. No other service is using ports 80 or 443"
    echo ""
    echo "You can verify DNS with: ${CYAN}dig +short $DOMAIN${NC}"
    echo ""
    read -p "DNS configured and ready? (y/N): " dns_ready
    
    if [[ $dns_ready =~ ^[Yy]$ ]]; then
        echo ""
        echo "Starting services to obtain SSL certificate..."
        
        # Create directories for certbot
        mkdir -p certbot/conf
        mkdir -p certbot/www
        
        # Start nginx for ACME challenge
        docker-compose up -d nginx
        sleep 5
        
        echo ""
        echo "Requesting SSL certificate from Let's Encrypt..."
        docker-compose run --rm certbot certonly \
            --webroot \
            --webroot-path=/var/www/certbot \
            --email $SSL_EMAIL \
            --agree-tos \
            --no-eff-email \
            -d $DOMAIN
        
        if [ $? -eq 0 ]; then
            echo ""
            echo -e "${GREEN}✓ SSL certificate obtained successfully!${NC}"
            
            # Update nginx.conf with actual domain
            sed -i "s|ssl_certificate /etc/letsencrypt/live/DOMAIN/|ssl_certificate /etc/letsencrypt/live/$DOMAIN/|g" nginx.conf
            
            echo -e "${GREEN}✓ Nginx configuration updated${NC}"
        else
            echo ""
            echo -e "${YELLOW}⚠ SSL certificate setup failed.${NC}"
            echo ""
            echo "You can try again later by running:"
            echo "  ${CYAN}docker-compose run --rm certbot certonly --webroot -w /var/www/certbot -d $DOMAIN${NC}"
        fi
    else
        echo ""
        echo -e "${YELLOW}Skipping SSL certificate setup.${NC}"
        echo ""
        echo "Configure DNS and obtain certificates later with:"
        echo "  ${CYAN}docker-compose run --rm certbot certonly --webroot -w /var/www/certbot -d $DOMAIN${NC}"
    fi
else
    # Development mode - create self-signed certificate
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo -e "${GREEN}🔒 Generating Self-Signed Certificate${NC}"
    echo ""
    
    mkdir -p nginx/ssl
    
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout nginx/ssl/key.pem \
        -out nginx/ssl/cert.pem \
        -subj "/C=US/ST=State/L=City/O=D&D PBP/CN=localhost" \
        2>/dev/null
    
    echo -e "${GREEN}✓ Self-signed certificate created${NC}"
    echo -e "${YELLOW}Note: Browsers will show a security warning (this is normal for development)${NC}"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${GREEN}╔════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║       🎉 Setup Complete! 🎉           ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════╝${NC}"
echo ""
echo -e "${CYAN}Configuration Summary:${NC}"
echo "  Domain:        $DOMAIN"
echo "  SSL:           $([ "$ENABLE_SSL" = "true" ] && echo "Enabled" || echo "Disabled (Development)")"
echo "  Debug Mode:    $DEBUG"
echo "  Environment:   $NODE_ENV"
echo ""
echo -e "${CYAN}Files Created:${NC}"
echo "  ✓ .env                 (Main configuration)"
echo "  ✓ .env.secrets         (Backup of secrets - keep safe!)"
if [ -f .env.backup.* ]; then
    echo "  ✓ .env.backup.*        (Previous configuration backup)"
fi
echo ""
echo -e "${CYAN}Next Steps:${NC}"
echo ""
echo "  ${GREEN}1.${NC} Start the application:"
echo "     ${CYAN}docker-compose up -d${NC}"
echo ""
echo "  ${GREEN}2.${NC} Check status:"
echo "     ${CYAN}docker-compose ps${NC}"
echo ""
echo "  ${GREEN}3.${NC} Access your application:"
if [ "$ENABLE_SSL" = "true" ]; then
    echo "     ${CYAN}https://$DOMAIN${NC}"
else
    echo "     ${CYAN}http://localhost${NC}"
fi
echo ""
echo "  ${GREEN}4.${NC} Register the first user (will be admin):"
if [ "$ENABLE_SSL" = "true" ]; then
    echo "     ${CYAN}https://$DOMAIN/register${NC}"
else
    echo "     ${CYAN}http://localhost/register${NC}"
fi
echo ""
echo -e "${YELLOW}⚠️  Important Security Notes:${NC}"
echo "  • Keep .env.secrets file safe (contains database passwords)"
echo "  • Never commit .env or .env.secrets to git"
echo "  • Set file permissions: ${CYAN}chmod 600 .env .env.secrets${NC}"
echo ""
echo -e "${GREEN}Happy gaming! 🎲${NC}"
echo ""
