"""create compendium table

Revision ID: 00bbc2fffaa5
Revises: 
Create Date: 2025-12-22 02:28:10.221901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00bbc2fffaa5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compendium',
    sa.Column('guid', sa.String(length=200), nullable=False),
    sa.Column('system', sa.String(length=50), nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('homebrew', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index('idx_system_type', 'compendium', ['system', 'entry_type'], unique=False)
    op.create_index(op.f('ix_compendium_entry_type'), 'compendium', ['entry_type'], unique=False)
    op.create_index(op.f('ix_compendium_homebrew'), 'compendium', ['homebrew'], unique=False)
    op.create_index(op.f('ix_compendium_name'), 'compendium', ['name'], unique=False)
    op.create_index(op.f('ix_compendium_system'), 'compendium', ['system'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compendium_system'), table_name='compendium')
    op.drop_index(op.f('ix_compendium_name'), table_name='compendium')
    op.drop_index(op.f('ix_compendium_homebrew'), table_name='compendium')
    op.drop_index(op.f('ix_compendium_entry_type'), table_name='compendium')
    op.drop_index('idx_system_type', table_name='compendium')
    op.drop_table('compendium')
    # ### end Alembic commands ###
